source: source
destination: site
markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:day/:title
url: http://octopress.org
multiviews: true
sass: false
haml: true
post_defaults:
  layout: default